language: cpp
compiler:
  - gcc

#For Ubuntu Trusty (14.04 LTS)
dist: trusty

env:
  matrix:
    - xGSL=0 xMPI=0 xPYTHON=0
    - xGSL=0 xMPI=0 xPYTHON=1
    - xGSL=0 xMPI=1 xPYTHON=0
    - xGSL=0 xMPI=1 xPYTHON=1
    - xGSL=1 xMPI=0 xPYTHON=0
    - xGSL=1 xMPI=0 xPYTHON=1
    - xGSL=1 xMPI=1 xPYTHON=0
    - xGSL=1 xMPI=1 xPYTHON=1
matrix:
  # do notify immediately about it when a job of a build fails.
  fast_finish: true
cache:
  apt: true 
  ccache: true
  pip: true
#virtualenv:
 # system_site_packages: true
#addons:
#  artifacts:
 #  debug: true

before_install:
  - echo $LANG
  - echo $LC_ALL

  # get repository for clang-3.6 stuff (including clang-format-3.6)
  - sudo sh -c 'echo -n "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.6 main" >> /etc/apt/sources.list'
  # add key from ^ repository
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -

  # update package repository status (-qq is more quiet)
  - sudo rm -rf /var/lib/apt/lists/*
  - ls /etc/apt/sources.list.d/
  - sudo apt-get update -qq

  # remove any obsolete libraries
  - sudo apt-get autoremove

  # from installation webpage http://www.nest-simulator.org/installation-2/#Standard_configuration
  - sudo apt-get install -y build-essential autoconf automake libtool libltdl7-dev libreadline6-dev libncurses5-dev libgsl0-dev python-all-dev python-numpy python-scipy python-matplotlib ipython

  # Install pip and cython
  - wget https://raw.github.com/pypa/pip/master/contrib/get-pip.py
  - sudo python get-pip.py
  - pip install --user cython==0.21.1
  - sudo pip install -U setuptools

  # MPI
  - sudo apt-get install -y openmpi-bin libopenmpi-dev

  # python testsuite nosetests
  - sudo apt-get install -y python-nose

  # static code analysis
  - sudo apt-get install -y libllvm3.6 clang-format-3.6 vera++

  # used for building cppcheck-1.69
  - sudo apt-get install -y libpcre3 libpcre3-dev

install: 
  - cython --version
  - python --version
 # - "mkdir -p $TRAVIS_BUILD_DIR/build/artefacts_upload"
before_script:
  - chmod +x build.sh 

script: ./build.sh  

after_failure:
  - cd $TRAVIS_BUILD_DIR/build
  - |
    echo "config.log: "
    cat config.log
    for i in $(find reports -type f); do
      echo "###########################"
      echo "File: $i"
      cat $i
    done
before_deploy:
  - cd $TRAVIS_BUILD_DIR/build
  - tar -zcvf configlog.tar.gz ./*.* 
  - tar -zcvf reports.tar.gz ./reports 
  - mkdir -p $TRAVIS_BUILD_DIR/build/artefacts_upload
  - cp configlog.tar.gz reports.tar.gz $TRAVIS_BUILD_DIR/build/artefacts_upload
  #- tar -zcvf $TRAVIS_BUILD_DIR/*.*/nupic_core-${TRAVIS_COMMIT}-${PLATFORM}64.tar.gz $TRAVIS_BUILD_DIR/build/artefacts_upload
  - echo "TRAVIS_BRANCH:" $TRAVIS_BRANCH 
  - echo "TRAVIS_BUILD_DIR:" $TRAVIS_BUILD_DIR
  - echo "TRAVIS_BUILD_ID:" $TRAVIS_BUILD_ID 
  - echo "TRAVIS_BUILD_NUMBER:" $TRAVIS_BUILD_NUMBER
  - echo "TRAVIS_COMMIT:" $TRAVIS_COMMIT 
  - echo "TRAVIS_COMMIT_RANGE:" $TRAVIS_COMMIT_RANGE 
  - echo "TRAVIS_JOB_ID:" $TRAVIS_JOB_ID
  - echo "TRAVIS_JOB_NUMBER:" $TRAVIS_JOB_NUMBER
  - echo "TRAVIS_PULL_REQUEST:" $TRAVIS_PULL_REQUEST 
  - echo "TRAVIS_SECURE_ENV_VARS:" $TRAVIS_SECURE_ENV_VARS 
  - echo "TRAVIS_REPO_SLUG:"  $TRAVIS_REPO_SLUG
  - echo "TRAVIS_TEST_RESULT:" $TRAVIS_TEST_RESULT
  
#S3 deployment    

deploy:
  provider: s3
  access_key_id: AKIAIC2R6KWR5DF2W6WQ
  secret_access_key:
    secure: MYu4cCqQtIOfLCJdeWjb1EThIUXgGMozSSuSImiEc6k7C5QMKkw2P006wQamsm1nmjFCTEMVlKOzk2YMBnS6qgtpZTZQK9+SBRZLyzFM2Us9katB52G/9XZa8s7/4dXV7zpDIZ3oSNDLoKmTRTWBLZ6zH6o01+68NR59XsTuUXM=
  bucket: "nest-travis-artefacts"
  region: eu-central-1
  skip_cleanup: true
  on:
    repo: nest/nest-simulator
    branch: s3_test
  local-dir: "$TRAVIS_BUILD_DIR/build/artefacts_upload"
  upload-dir: "$TRAVIS_REPO_SLUG/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER"
  acl: bucket_owner_full_control
